Traceback (most recent call last):
  File "/home/rvk/utils/cno_utils.py", line 242, in evaluate_cno_all_resolution
    loss = loss_fn(batch_pred, batch_y)
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/utils/cno_utils.py", line 46, in forward
    x.reshape(num_examples, -1) - y.reshape(num_examples, -1), 2, 1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (786432) must match the size of tensor b (3072) at non-singleton dimension 1
Traceback (most recent call last):
  File "/home/rvk/utils/cno_utils.py", line 242, in evaluate_cno_all_resolution
    loss = loss_fn(batch_pred, batch_y)
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/utils/cno_utils.py", line 46, in forward
    x.reshape(num_examples, -1) - y.reshape(num_examples, -1), 2, 1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (786432) must match the size of tensor b (12288) at non-singleton dimension 1
Traceback (most recent call last):
  File "/home/rvk/utils/cno_utils.py", line 242, in evaluate_cno_all_resolution
    loss = loss_fn(batch_pred, batch_y)
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/utils/cno_utils.py", line 46, in forward
    x.reshape(num_examples, -1) - y.reshape(num_examples, -1), 2, 1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (786432) must match the size of tensor b (49152) at non-singleton dimension 1
Traceback (most recent call last):
  File "/home/rvk/utils/cno_utils.py", line 242, in evaluate_cno_all_resolution
    loss = loss_fn(batch_pred, batch_y)
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rvk/miniconda3/envs/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/utils/cno_utils.py", line 46, in forward
    x.reshape(num_examples, -1) - y.reshape(num_examples, -1), 2, 1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (786432) must match the size of tensor b (196608) at non-singleton dimension 1
